version: '3.8'

services:
  web:
    build: .
    platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      # Removed the Redis dependency as it's hosted externally
    command: python manage.py runserver 0.0.0.0:8000
