# Generated by Django 5.1.1 on 2024-10-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSheetTracker',
        ),
    ]
