# Generated by Django 5.1.1 on 2024-10-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_usersheettracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersheet',
            old_name='Sheet_name',
            new_name='sheet_name',
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='race',
            field=models.IntegerField(choices=[(1, 'Human'), (2, 'Gnome'), (3, 'Elf'), (4, 'Halfling')], default=1),
            preserve_default=False,
        ),
    ]
