# Generated by Django 5.1.1 on 2024-11-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_elfsheets_active_gnomesheets_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='sheet_name',
        ),
    ]
