# Generated by Django 5.1.1 on 2024-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_elfsheets_inventory_gnomesheets_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='char_name',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
