# Generated by Django 5.1.1 on 2024-11-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_elfsheets_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
