# Generated by Django 5.1.1 on 2025-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_inventoryitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='char_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='elfsheets',
            name='char_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gnomesheets',
            name='char_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='halflingsheets',
            name='char_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='humansheets',
            name='char_name',
            field=models.CharField(max_length=10),
        ),
    ]
