# Generated by Django 5.1.1 on 2025-04-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_charactersheet_char_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elfsheets',
            old_name='hitpoints',
            new_name='CurrentHitPoints',
        ),
        migrations.RenameField(
            model_name='gnomesheets',
            old_name='hitpoints',
            new_name='CurrentHitPoints',
        ),
        migrations.RenameField(
            model_name='halflingsheets',
            old_name='hitpoints',
            new_name='CurrentHitPoints',
        ),
        migrations.RenameField(
            model_name='humansheets',
            old_name='hitpoints',
            new_name='CurrentHitPoints',
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='MaxHitPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='TempHitPooints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='MaxHitPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='TempHitPooints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='MaxHitPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='TempHitPooints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humansheets',
            name='MaxHitPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humansheets',
            name='TempHitPooints',
            field=models.IntegerField(default=0),
        ),
    ]
