# Generated by Django 5.1.1 on 2025-04-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_hitpoints_elfsheets_currenthitpoints_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humansheets',
            old_name='TempHitPooints',
            new_name='TempHitPoints',
        ),
    ]
