# Generated by Django 5.1.1 on 2025-04-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_temphitpooints_humansheets_temphitpoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elfsheets',
            old_name='TempHitPooints',
            new_name='TempHitPoints',
        ),
        migrations.RenameField(
            model_name='gnomesheets',
            old_name='TempHitPooints',
            new_name='TempHitPoints',
        ),
        migrations.RenameField(
            model_name='halflingsheets',
            old_name='TempHitPooints',
            new_name='TempHitPoints',
        ),
    ]
