# Generated by Django 5.1.1 on 2025-05-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_temphitpooints_elfsheets_temphitpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humansheets',
            name='ChosenProficiencies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
