# Generated by Django 5.1.1 on 2025-05-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_humansheets_chosenproficiencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='elfsheets',
            name='ChosenProficiencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='ChosenProficiencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='ChosenProficiencies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
