# Generated by Django 5.1.1 on 2024-11-07 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_humansheets_stat_charisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elfsheets',
            name='char_gold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='stat_Charisma',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='stat_Constitution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='stat_Dexterity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='stat_Intelligence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='stat_Strength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='stat_Wisdom',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='char_gold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='stat_Charisma',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='stat_Constitution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='stat_Dexterity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='stat_Intelligence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='stat_Strength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='stat_Wisdom',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='char_gold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='stat_Charisma',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='stat_Constitution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='stat_Dexterity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='stat_Intelligence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='stat_Strength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='stat_Wisdom',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='humansheets',
            name='char_gold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='humansheets',
            name='stat_Charisma',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='humansheets',
            name='stat_Constitution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='humansheets',
            name='stat_Dexterity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='humansheets',
            name='stat_Intelligence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='humansheets',
            name='stat_Strength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='humansheets',
            name='stat_Wisdom',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
    ]
