# Generated by Django 5.1.1 on 2024-11-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_charactersheet_sheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='elfsheets',
            name='race',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='base.charactersheet'),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='race',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.charactersheet'),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='race',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='base.charactersheet'),
        ),
        migrations.AddField(
            model_name='humansheets',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.charactersheet'),
        ),
    ]
