# Generated by Django 5.1.1 on 2024-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_charactersheet_char_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='elfsheets',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='gnomesheets',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='halflingsheets',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='humansheets',
            name='inventory',
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='inventory',
            field=models.ManyToManyField(to='base.inventoryitem'),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='inventory',
            field=models.ManyToManyField(to='base.inventoryitem'),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='inventory',
            field=models.ManyToManyField(to='base.inventoryitem'),
        ),
        migrations.AddField(
            model_name='humansheets',
            name='inventory',
            field=models.ManyToManyField(to='base.inventoryitem'),
        ),
    ]
