# Generated by Django 5.1.1 on 2024-11-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_inventoryitem_remove_elfsheets_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elfsheets',
            name='hitpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elfsheets',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='hitpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gnomesheets',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='hitpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='halflingsheets',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='humansheets',
            name='hitpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='humansheets',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
