# Generated by Django 5.1.1 on 2024-11-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_elfsheets_hitpoints_elfsheets_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elfsheets',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='gnomesheets',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='halflingsheets',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='humansheets',
            name='inventory',
        ),
        migrations.CreateModel(
            name='CharacterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.charactersheet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='inventory',
            field=models.ManyToManyField(related_name='characters', through='base.CharacterInventory', to='base.inventoryitem'),
        ),
    ]
