# Generated by Django 5.1.1 on 2024-11-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='extra_sheets',
            field=models.IntegerField(default=0),
        ),
    ]
